### PR TITLE
Remove duplicated text from adding UK chapters

### PR DESCRIPTION
**Pull request by evestera**
I understand that this ebook is the US edition with the two extra chapters from the UK edition added back in. However, that leaves some redundant text at the beginning of chapter 3-14 which is there in the US edition to keep the necessary parts of the removed chapter. According to [this blog post](https://note.mu/itomaru/n/n6518ae66c23b) there are some other parts as well that were removed from the UK edition that – as far as I can tell – have not been restored to this edition, but as using the UK edition complicates copyright matters a bit – at least outside the US – I don't feel comfortable adding those parts here myself.

### CODE REVIEW

**Comment by acabal** [comment]
We're using this print edition as a guide: https://catalog.hathitrust.org/Record/100208678

Does your change occur in that print edition? If not, what does it do instead?

**Comment by evestera** [comment]
Yes, that is the edition I looked at to make the change. There are at least also some paragraphs in Chapter 1 of the linked UK edition that is missing in this ebook/repo as well, that I verified before realising the complicated copyright status of the book.

**Comment by acabal** [comment]
What copyright complications are you referring to? It was a 1921 publication which clears it in the US (and most likely worldwide too unless the translator was particularly long-lived)

**Comment by evestera** [comment]
Scaramouche was published in London in 1921, and Sabatini died in 1950. In the US there is a special case for books published before 1923, and there was a US edition which this probably applies to, which should make that edition public domain everywhere. But for the UK edition without this exception it is life + 70, which means copyright expires January 2021 in e.g. Norway, where I live, even though it is also public domain in the US. Now, I may have misunderstood some part of this, but for reference, Hathi Trust will give me full view of the US edition, but a limited view of the UK edition, due to the fact that I am outside the US and trying to view a work published outside the US.

**Comment by acabal** [comment]
OK, I see what you mean. Since the SE project is US-based we're only concerned with US copyright rules which is why we can work on this ebook.

Are you able to fix the missing parts of Chapter 1 as well?

**Pull request merged**
